[package]
name = "probe-rs-rtt"
version = "0.1.0"
edition = "2018"
description = "Host side implementation of the RTT (Real-Time Transfer) I/O protocol over probe-rs"
license = "MIT"
authors = ["Matti Virkkunen <mvirkkunen@gmail.com>"]

[dependencies]
probe-rs = "0.6.0"
scroll = "0.10.1"
thiserror = "1.0.11"
